<?php

/**
 * BaseBuilding
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Invoice
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getInvoice() Returns the current record's "Invoice" collection
 * @method Building            setId()      Sets the current record's "id" value
 * @method Building            setName()    Sets the current record's "name" value
 * @method Building            setInvoice() Sets the current record's "Invoice" collection
 * 
 * @package    MyS
 * @subpackage model
 * @author     Ferbal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBuilding extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('building');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Invoice', array(
             'local' => 'id',
             'foreign' => 'building_id'));
    }
}