<?php

/**
 * BuildingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Building');
    }
}