<?php

/**
 * InvoiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceTable extends Doctrine_Table {
  /**
   * Returns an instance of this class.
   *
   * @return object InvoiceTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Invoice');
  }

  public static function doSelectJoin($query) {
    $rootAlias = $query->getRootAlias();
 
    return $query->select($rootAlias . '.*, s.name, b.name, p.date')
      ->leftJoin($rootAlias . '.Supplier s')
      ->leftJoin($rootAlias . '.PaymentDate p')
      ->leftJoin($rootAlias . '.Building b');
  }

}