<?php

/**
 * Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MyS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invoice extends BaseInvoice {

  public function save(Doctrine_Connection $conn = null) {
    if ($this->isNew()) {
 //       foreach()
 //       var_dump($this->Invoices->supplier_id);
          //var_dump($this);
          //die;
          
      $this->supplier_id = $this->PaymentDate->supplier_id;
    }

    return parent::save($conn);
  } 

  public function delete(Doctrine_Connection $conn = null) {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Url'));

    $result = parent::delete($conn);

    return $result;
  }
  
}