generator:
#  class: sfDoctrineGenerator
  class: mpRealtyAdminDoctrineGenerator
  param:
    model_class:           PaymentDate
#    theme:                 admin
    theme:                 mpReality
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          payment_date
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        date: { label: Fecha de Pago }
        supplier: { label: Proveedor, is_real: true  }
        total_value: { label: Importe Total }
        paid: { labe: Abonado }
      list:
        title: Listado Pagos
        display: [=date, supplier, total_value, paid]
        sort: [date, desc]
        table_method: doSelectJoin
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Editando Fecha de pago %%date%% | %%supplier_id%%
      new:
        title: Nueva Fecha de Pago
