generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Supplier
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          supplier
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Nombre }
        address: { label: Dirección }
        email: { label: E-mail }
        phone: { label: Teléfono }

      list:
        title: Listado de Proveedores
        display: [=name, address, email, phone]
        sort: [name, asc]
        max_per_page: 10

      filter:
        display: [name, email, phone]
      form:    ~
      edit:
        title: Editando Proveedor %%name%%
      new:
        title: Nuevo Proveedor